services:
  - type: web
    name: workshop-assistant-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    disk:
      name: workshop-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DB_PATH
        value: /data/auto_db.sqlite
      - key: UPLOAD_PATH
        value: /data/uploads
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: workshop-assistant-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python agent.py
    rootDir: backend
    disk:
      name: workshop-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DB_PATH
        value: /data/auto_db.sqlite
      - key: UPLOAD_PATH
        value: /data/uploads
      - key: LIVEKIT_API_KEY
        sync: false
      - key: LIVEKIT_API_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false 